# Generated by Django 5.1.2 on 2024-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_officestaffdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarianDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Post', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('UserNaMe', models.CharField(blank=True, max_length=100, null=True)),
                ('PassWoRd', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
