# Generated by Django 5.1.2 on 2024-10-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_librariandb'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Class_Name', models.CharField(max_length=50)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Post', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('UserNaMe', models.CharField(blank=True, max_length=100, null=True)),
                ('PassWoRd', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feeshistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.studentdb'),
        ),
        migrations.AlterField(
            model_name='libraryhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.studentdb'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
