# Generated by Django 5.1.2 on 2024-10-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_remove_studentdb_pin_remove_studentdb_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='PassWoRd',
        ),
    ]
