# Generated by Django 5.1.2 on 2024-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_studentdb_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='Phone',
        ),
        migrations.AddField(
            model_name='studentdb',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
